FROM node:20-bullseye

RUN apt-get update && apt-get install -y imagemagick curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY . .

CMD ["node", "server.js"]
